### ISSUE TITLE
download and build BASIS automatically if not available in supplied basis template

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#282]
Requiring users of tools based off of BASIS to download and install BASIS before anything else is burdensome, we should make it so BASIS will download and install itself automatically (perhaps super build style) if it is not available.

**Comment by schuhschuh** [comment]
I think this has been implemented with the `BasisBootstrapping.cmake` module. Also, projects that don't require the full blown CMake BASIS project but only it's CMake modules can include these directly in their source tree using either `git submodule` or `git subtree` (recommended). See README of https://github.com/schuhschuh/cmake-basis-modules for more on this.
