### ISSUE TITLE
toplevel module dependency should make the dependency always build

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#315]
Should top level projects be able to have modules specified as dependencies?

If allowed, then when a module is a required dependency the `MODULE_<projectname>` variable should not be possible to change.

Related issues:
#326 
#333

**Comment by schuhschuh** [comment]
> easy way to extract dependency list

I've recently added functions to the `ProjectTools.cmake` module which might be what you were looking for regarding getting the dependency list of a module:
- [basis_get_module_info](https://github.com/schuhschuh/cmake-basis/blob/50a6fa0f92d796af6130e29b5cc78d91ac15d9eb/src/cmake/modules/ProjectTools.cmake#L885)
- [basis_check_if_module_depends_on_package](https://github.com/schuhschuh/cmake-basis/blob/50a6fa0f92d796af6130e29b5cc78d91ac15d9eb/src/cmake/modules/ProjectTools.cmake#L1233)
- [basis_check_if_package_is_needed_by_modules](https://github.com/schuhschuh/cmake-basis/blob/50a6fa0f92d796af6130e29b5cc78d91ac15d9eb/src/cmake/modules/ProjectTools.cmake#L1296)

**Comment by schuhschuh** [comment]
> way to set modules to ON by default covered in issue

You can specify the `PROJECT_DEFAULT_MODULES` list in the `basis_project` in `BasisProject.cmake` file of top-level project. See [MIRTK BasisProject.cmake file](https://github.com/BioMedIA/MIRTK/blob/7045009da70cb8355610f5d3f9d8efe12a3bb0fd/BasisProject.cmake#L79) for example.
