### ISSUE TITLE
Allow user to define which modules are enabled by default

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#326]
At the moment not straightforward because you cannot tell whether currently it's set to the BASIS default or if the user already changed it... Sure, it would be a useful feature to have as generally users of your package may go with the defaults and maybe you don't want all modules ON by default (via BUILD_ALL_MODULES which I believe BASIS sets to ON by default).

If the use could set these variables before BASIS adds them as options to the cache, BASIS could just do that but keep the current value... but I fear at the moment the variables are added by BASIS before config/Settings.cmake is included.

As discussed in commit 5cb79233e31ad2ac24e3fda5a7a0c2c395c11a49

Related issues:
#333 
#315

**Comment by schuhschuh** [comment]
This issue is back on my list of more urgent things to address as I am finally using the modules feature myself in a project where the new "All modules ON by default" is very unpleasant. Need to find better resolution than the one of #333.

**Comment by schuhschuh** [comment]
The list of modules to be enabled by default can be specified by the (top-level) project developer with the new ```DEFAULT_MODULES``` option of ```basis_project``` in the ```BasisProject.cmake``` file of the top-level project. The ```BUILD_MODULES_BY_DEFAULT``` option is no longer available. Instead, set ```DEFAULT_MODULES``` equal ```ALL```. Alternatively, a user can set ```BUILD_ALL_MODULES``` to ON which could be set to ON by default in the root CMakeLists.txt before the ```basis_project_begin/basis_project_impl``` call. A module developer can exclude their module by default from ```BUILD_ALL_MODULES``` by adding the ```EXCLUDE_FROM_ALL``` option to the ```basis_project``` command in the ```BasisProject.cmake``` file of the project module/subproject. A user can exclude certain modules from ```BUILD_ALL_MODULES``` using the CMake command-line argument ```-D BUILD_ALL_MODULES=ON -D EXCLUDE_<MODULE>_FROM_ALL=ON```. A module that is by default excluded from ```BUILD_ALL_MODULES``` via the ```EXCLUDE_FROM_ALL``` option added by the module developer, can be added again to this list of all modules by a user on the command-line using ```-D EXCLUDE_<MODULE>_FROM_ALL=OFF```.

- [ ] Add this information to the user manual.

**Comment by ahundt** [comment]
sounds sensible

**Comment by schuhschuh** [comment]
As usual, updating and extending the documentation remains to be done... another time.
