### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#418]
We should add support for C++11. Probably enable this the same way MATLAB is enabled, but instead specify C++11. Alternately it could be C++{11}, the other way MATLAB components can be specified. 

Here is a basic C++11 script

``` cmake
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_LIST_DIR})

# Enable C++11
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
elseif(COMPILER_SUPPORTS_CXX0X)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
else()
        message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()
```

**Comment by schuhschuh** [comment]
Maybe this would be better added as a new ```LANGUAGES``` option of the ```basis_project``` macro in the ```BasisProject.cmake``` file? For example,

```cmake
basis_project (
  NAME          "BASIS"
  VERSION       "0.0.0"
  LANGUAGES     C++{11} Python Java Jython Bash Matlab
  # other project meta-data and list of third-party dependencies
)
```

where I would alternatively also accept ```CXX``` for C++ as does the CMake [project](https://cmake.org/cmake/help/v3.4/command/project.html) command.

Specifying a scripting language such as Python would then make BASIS look for an installation of the interpreter. Currently, BASIS itself specifies ```PythonInterp``` as optional dependency instead. But then we might also need a corresponding ```OPTIONAL_LANGUAGES``` setting. Need to think about this further and look into the implementation specifics.

But for the C++11 compiler flag addition, I think ```LANGUAGES C++{11}``` makes sense.

**Comment by schuhschuh** [comment]
Also, having such ```LANGUAGES``` option for ```basis_project```, we could pass some of its entires understood by CMake's ```project``` command on to it.

**Comment by schuhschuh** [comment]
Minor correction. Version numbers are appended with a dash for dependencies, i.e., it should be ```CXX-11``` instead of ```CXX{11}```.

**Comment by schuhschuh** [comment]
I've added the ```LANGUAGES``` option to ```basis_project``` in the ```mirtk``` branch of the [CMake BASIS Modules](https://github.com/schuhschuh/cmake-basis-modules/commit/bc35d9c0465c260726cb557f921e18f2d4935b09).

**Comment by ahundt** [comment]
does the latest CMake have anything to say on this? Looks like [CXX_STANDARD](https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD) and [CXX_EXTENSIONS](https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_EXTENSIONS.html#prop_tgt:CXX_EXTENSIONS) may be what we want.

**Comment by schuhschuh** [comment]
Thanks for pointing these out, I wasn't aware of the new CXX_STANDARD
target property added in CMake 3.1. In this case, BASIS doesn't need to do
anything itself. Unless we want to set the property implicitly when
LANGUAGES is CXX-?? to the number following the dash. Could still be
overridden for single tagrets by setting the property explicitly to a
different value.
