### ISSUE TITLE
Support IDL formats

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#419]
IDL formats include google protocol buffers, google flatbuffers, rosmsgs, opensplice IDL formats, etc. 

They generally consist of an IDL format, such as `protoc` or `flatc`, and IDL files. Frequently, the IDL files should be installed for other languages to use, as should their generated output formats. 

There should be a convenient and reasonable recommended way to lay out these files and the generated headers specified by BASIS, perhaps under [Standards](http://opensource.andreasschuh.com/cmake-basis/standard/fhs.html). Note this may also include supporting other languages, for example protocol buffers supports a superset of the languages BASIS supports.

**Comment by schuhschuh** [comment]
I'll leave this up to you as I have no clue about these formats and not encountered any need for them myself... not a robotics guy ;)

**Comment by ahundt** [comment]
Not even primarily for robotics (except rosmsgs), used in facebook's apps, google's apps, really any use case where serialization and data transport between machines is needed.
