### ISSUE TITLE
Could not import extension doxylink

### ISSUE THREAD

**Issue by ShahriarSefati** [cmake-basis/legacy#436]
I am using Ubuntu 14.04, installed sphinx and doxylink and I get this error when I do `make doc`:

    Extension error:    
    Could not import extension doxylink (exception: No module named doxylink)

**Comment by schuhschuh** [comment]
The doxylink extension is actually included in the BASIS source package and should have been picked up fine. Are you still having this issue? Maybe some more details would be helpful.
