### ISSUE TITLE
Can't build both shared and static versions of libraries

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#441]
A third party library I'm trying to use builds both the static and shared versions of a library, and BASIS didn't seem to be able to handle that.

**Comment by schuhschuh** [comment]
Can you be more precise ? How does the library build these, are they located in the same directory, do they have the same file name with only differing file extension or does the name differ (e.g., by a "d" suffix of the library name) ? Does the library provide a CMake configuration file ? And most importantly, what means "BASIS didn't seem to be able to handle that" ? What is the problem you encounter, specific linker error... or does it simply not pick up the library you are expecting ?

My feeling is that is more likely related to CMake's ```find_library``` command. It looks for libraries with extensions given in ```CMAKE_FIND_LIBRARY_SUFFIXES```. I think the default is that shared libraries are preferred over static libraries.

**Comment by schuhschuh** [comment]
And the title suggests you want to build shared and static versions of your own libraries. In the static case, you most likely want to link to the static third-party library while in the shared case you could link to either the shared or the static third-party library.

There is currently no particular mechanism in BASIS to automate this. If your third-party library uses CMake itself, it should export separate targets for the shared and static libraries. These would then be imported in your project, e.g., as "thirdparty-lib-target-shared" and "thirdparty-lib-target-static". Then you can add two library targets to your project, one "SHARED" and the other "STATIC" and specify either one of the imported third-party library targets as link dependency.

**Comment by ahundt** [comment]
I think Improvements on the method you described are possible. It may be possible to just put both `STATIC` and `SHARED` for current versions of CMake. not sure.

This blog entry also had an interesting technique:
https://navaneeth.github.io/blog/2013/07/28/building-static-and-shared-libraries-using-cmake/

**Comment by schuhschuh** [comment]
Interesting, but I don't think that it's an all purpose solution. Fine with me if that is possible, but as already one of the commenters notes, there are often differences in the compilation and preprocessor flags of static and shared libraries.
