### ISSUE TITLE
Support non-BASIS external build targets / subproject in subdirectory

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#442]
I have an "external" library I'm calling add_subdirectory on within a basis project, but I can't link other libraries to the "external" one because some variables aren't set when BASIS isn't used in an add_library call. What can I do to work around this without modifying the other project?

example problem in `src/CMakeLists.txt`:

``` cmake
basis_add_subdirectory(external_dir)

basis_add_library(mylib.cpp)
basis_target_link_libraries(mylib external_lib)
```

Example error:

```
CMake Error at /usr/local/share/basis/cmake-modules/CommonTools.cmake:2975 (message):
  Failed to get directory of SHARED_LIBRARY camodocal_calib! Check
  implementation of basis_get_target_location() and make sure that the
  required *INSTALL_DIRECTORY property is set on the target!
Call Stack (most recent call first):
  /usr/local/share/basis/cmake-modules/TargetTools.cmake:2544 (basis_get_target_location)
  /usr/local/share/basis/cmake-modules/TargetTools.cmake:2466 (basis_set_target_install_rpath)
  /usr/local/share/basis/cmake-modules/ProjectTools.cmake:2068 (basis_finalize_targets)
  /usr/local/share/basis/cmake-modules/ProjectTools.cmake:2168 (basis_project_end)
  CMakeLists.txt:84 (basis_project_impl)
```

**Comment by schuhschuh** [comment]
This looks like a bug.

The ```basis_get_target_location``` with ```POST_INSTALL_PATH``` option requires that the ```LIBRARY_INSTALL_DIRECTORY``` target property is set. It is called by ```basis_set_target_install_rpath``` which you probably don't even want to be called on "external" targets.

A workaround would be to set ```BASIS_INSTALL_RPATH = OFF```.

**Comment by schuhschuh** [comment]
You could also consider overwriting the ```add_library``` function. BASIS itself uses:

```
function (add_library TARGET_UID)
  _add_library (${TARGET_UID} ${ARGN})
  list (FIND ARGN IMPORTED IDX)
  if (IDX EQUAL 1)
    basis_add_imported_target ("${TARGET_UID}" "${ARGV1}")
  else ()
    basis_set_project_property (APPEND PROPERTY TARGETS "${TARGET_UID}")
  endif ()
endfunction ()
```

If your "external" targets were not added to the ```TARGETS``` "project property", they would not be dealt with in ```basis_finalize_targets```.

So you could either prevent these to be added to this list, or remove them from the list after the ```add_subdirectory```:

```
basis_get_project_property (TARGETS)
list(REMOVE TARGETS ...)
basis_set_project_property(PROPERTY TARGETS "${TARGETS}")
```

**Comment by schuhschuh** [comment]
Any chance your change for #448 was related to this issue you encountered ? This would give us some more hints on what you were trying to fix with this.

**Comment by ahundt** [comment]
Perhaps, unfortunately I don't remember. To reproduce the issue here however, simply take any repository without basis and make it a subdirectory of a folder like `/thirdparty` and put it in the `SOURCE_DIRS` list. 

One option to deal with the problem include simply providing an expanded error message, perhaps containing a link to a documentation page with how to deal with this.

Options include:

- modifying the other code to use basis too
- building the library as an external project
- installing the library on your system and using a find script

I think this can't really be dealt with "automatically" because the installers are affected by how the cmake script works.

**Comment by schuhschuh** [comment]
The fix of this issue might involve adding a new function ```basis_add_external_target``` which ensures that BASIS treats the target as a non-BASIS target just like it does with imported targets. The overridden ```add_library``` and ```add_executable``` functions will be default then call this function for non-imported targets. A special flag could be passed by ```basis_add_executable``` and ```basis_add_library``` functions to indicate that it is not an external target, but that the target is added via either of these functions (or one of their specializations).

I would consider this rather a new feature than a bug as it extends the functionality of BASIS to support the inclusion of non-BASIS configured CMake code directly in a project via ```add_subdirectory```.

Let's postpone this a bit further.

**Comment by ahundt** [comment]
That also sounds reasonable
