### ISSUE TITLE
Homebrew recipe for cmake-basis

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#450]
I've created a homebrew recipe for cmake-basis. We should incorporate it into the docs, and perhaps try submitting it to the main github.com/homebrew/homebrew repository.

use it as follows:

```bash
# first install homebrew http://brew.sh
brew tap ahundt/robotics
brew install cmake-basis --devel -v
```

One issue is outstanding. It currently only works with:
`brew install cmake-basis --devel -v` 

because the current cmake-basis release is not compatible with cmake 3.3. Fortunately the version in the devel branch is.

**Comment by jkhoogland** [comment]
Hi, 
just tried to install on OSX,
if the cask version of cmake is installed, 
```
cask cask install cmake
```
this script currently aborts with the following message:

```
[2015.09.11:08.32][Jiri@JiriMBP:~/lib/cpp/cmake-related/cmake-basis]$  brew install cmake-basis --devel -v

==> Installing cmake-basis from ahundt/homebrew-robotics
Error: You must `brew link cmake' before ahundt/robotics/cmake-basis can be installed
```

because of

```
  brew link --overwrite --dry-run cmake
[2015.09.11:08.32][Jiri@JiriMBP:~/lib/cpp/cmake-related/cmake-basis]$  ll /usr/local/bin/ccmake
lrwxr-xr-x 1 Jiri admin 69 Jul 13 18:51 /usr/local/bin/ccmake -> /opt/homebrew-cask/Caskroom/cmake/3.2.2/CMake.app/Contents/bin/ccmake*
```

might be useful to make the script work with the cask version of cmake as well ?
Regards
Jiri

**Comment by jkhoogland** [comment]
Hi,
the script should probably check if python3 (eg anaconda) etc is already installed, and used, before installing as basis will not run with python3...
Regards
Jiri

**Comment by ahundt** [comment]
try tapping my formula and installing with that:
https://github.com/ahundt/homebrew-robotics

**Comment by ahundt** [comment]
oh wait didn't read the stuff above this :-) re-reading now

**Comment by ahundt** [comment]
oh why did you choose to use the cask version instead of the homebrew provided version? I'd be happy to incorporate a pull request as well if you know how to fix it

**Comment by ahundt** [comment]
Is it definitely python3 or does 2.7 work?

On Friday, September 11, 2015, jkhoogland <notifications@github.com> wrote:

> Hi,
> the script should probably check if python3 (eg anaconda) etc is already
> installed, and used, before installing as basis will not run with python3...
> Regards
> Jiri
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schuhschuh/cmake-basis/issues/450#issuecomment-139544683>
> .
>


-- 

Cheers!
Andrew Hundt

**Comment by jkhoogland** [comment]
* cask version
no specific reason, it has a proper cmake.app.
but it is a bit annoying to have to uninstall and install the other cmake version.. 
should not be necessary. 
* python
The following failure occurs with anaconda/python 3.4 switched on,
(it works when setting to python 2.7)
```
[2015.09.11:10.36][Jiri@JiriMBP:~/lib/cpp/cmake-related/basis-related]$  python --version
Python 3.4.3 :: Anaconda 2.3.0 (x86_64)
[2015.09.11:10.36][Jiri@JiriMBP:~/lib/cpp/cmake-related/basis-related]$  basisproject
  File "/usr/local/bin/basisproject", line 430
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by schuhschuh** [comment]
@ahundt Would it be possible to complete the recipe ? I.e.,

- [ ] Use ```http://schuhschuh.github.io/cmake-basis/``` as homepage URL
- [ ] Change version tag to ```v3.2.0``` which will be the next release
- [ ] CMake should be a required dependency, it is also needed after the build and installation of BASIS
- [ ] Add Sphinx as recommended dependency: ```depends_on "Sphinx" => [:recommended, :python]```?
     - Or copied from [cmake formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cmake.rb):
     ```
  resource "pygments" do
    url "https://pypi.python.org/packages/source/P/Pygments/Pygments-2.0.2.tar.gz"
    sha256 "7320919084e6dac8f4540638a46447a3bd730fca172afc17d2c03eed22cf4f51"
  end

  resource "docutils" do
    url "https://pypi.python.org/packages/source/d/docutils/docutils-0.12.tar.gz"
    sha256 "c7db717810ab6965f66c8cf0398a98c9d8df982da39b4cd7f162911eb89596fa"
  end

  resource "markupsafe" do
    url "https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz"
    sha256 "a4ec1aff59b95a14b45eb2e23761a0179e98319da5a7eb76b56ea8cdc7b871c3"
  end

  resource "jinja2" do
    url "https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.8.tar.gz"
    sha256 "bc1ff2ff88dbfacefde4ddde471d1417d3b304e8df103a7a9437d47269201bf4"
  end

  resource "sphinx" do
    url "https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.3.1.tar.gz"
    sha256 "1a6e5130c2b42d2de301693c299f78cc4bd3501e78b610c08e45efc70e2b5114"
  end
```
- [ ] Add language interpreters (i.e., [BASH], Perl, Jython) as optional dependencies to have ```--with-<lang>```, if this option not given, ```-DUSE_<lang>=OFF``` should be added to the CMake command
      - option "with-bash", "Enable support for Bash development"
      - option "with-perl", "Enable support for Perl development"
      - option "with-python", "Enable support for Python development"
      - option "with-jython", "Enable support for Jython development"
      - ```depends_on "jython" => :optional```
      - ```depends_on "perl" => :optional```
- [ ] Add options for build of BASIS Utilities for specific language
      - option "with-cxx-utilities", "Install C++ utilities"
      - option "with-bash-utilities", "Install Bash utilities"
      - option "with-perl-utilities", "Install Perl utilities"
      - option "with-python-utilities", "Install Python utilities"
- [ ] Add option for installation of project tool
      - option "with-project-tool", "Install basisproject tool"
- [ ] Add homebrew/science/insighttoolkit (ITK) as optional dependency
- [ ] Add test execution, possibly only a subset (test_basisproject and test_utilities take a moment, but are on the other side quite important)

How to add optional CMake arguments based on formula options:
```
cmake_args = std_cmake_args
cmake_args << "-DBUILD_DOCUMENTATION=OFF"
if build.with? "sphinx"
  cmake_args << "-DUSE_Sphinx=ON"
else
  cmake_args << "-DUSE_Sphinx=OFF"
end
if build.with? "perl"
  cmake_args << "-DUSE_Perl=ON"
else
  cmake_args << "-DUSE_Perl=OFF"
end
if build.with? "perl-utilities"
  cmake_args << "-DBUILD_BASIS_UTILITIES_FOR_PERL=ON -DUSE_Perl=ON"
else
  cmake_args << "-DBUILD_BASIS_UTILITIES_FOR_PERL=OFF"
end
if build.with? "python"
  cmake_args << "-DUSE_PythonInterp=ON"
else
  cmake_args << "-DUSE_PythonInterp=OFF"
end
if build.with? "python-utilities"
  cmake_args << "-DBUILD_BASIS_UTILITIES_FOR_PYTHON=ON -DUSE_PythonInterp=ON"
else
  cmake_args << "-DBUILD_BASIS_UTILITIES_FOR_PYTHON=OFF"
end
if build.with? "jython"
  cmake_args << "-DUSE_JythonInterp=ON"
else
  cmake_args << "-DUSE_JythonInterp=OFF"
end
if build.with? "project-tool"
  cmake_args << "-DBUILD_PROJECT_TOOL=ON"
else
  cmake_args << "-DBUILD_PROJECT_TOOL=OFF"
end
system "cmake", "-G", "Unix Makefiles", "..", *cmake_args
```

**Comment by ahundt** [comment]
might be some time before I can get to this

**Comment by ahundt** [comment]
Most of it is there now! It wasn't happy with Jython, but I was able to build the devel version successfully with the following flags:

    brew update; brew reinstall cmake-basis --devel -v

**Comment by schuhschuh** [comment]
Nice. I've forked homebrew and added the formula: https://github.com/schuhschuh/homebrew/commit/c2a5f809c68be9aa40ba00907bc6b3eb99c4eaea

Will update this file with the missing features. You think it's possible to collaborate directly on it? I.e., that you can push your changes directly?

**Comment by ahundt** [comment]
Yeah if needed I can. I don't expect we will need to often.

On Thursday, October 8, 2015, Andreas Schuh <notifications@github.com>
wrote:

> Nice. I've forked homebrew and added the formula: schuhschuh/homebrew@
> c2a5f80
> <https://github.com/schuhschuh/homebrew/commit/c2a5f809c68be9aa40ba00907bc6b3eb99c4eaea>
>
> Will update this file with the missing features. You think it's possible
> to collaborate directly on it? I.e., that you can push your changes
> directly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schuhschuh/cmake-basis/issues/450#issuecomment-146696164>
> .
>


-- 

Cheers!
Andrew Hundt

**Comment by schuhschuh** [comment]
I will exclude this issue as somewhat independent (Homebew recipe is not actually in the BASIS source tree) from the release milestone. The Homebrew installation steps can be added to the web page later on.

**Comment by ahundt** [comment]
I've been using the script for a while now and it seems to work well. One possible change would be disabling the documentation component by default, because homebrew rebuilds it every time around. Your version put into homebrew/homebrew can probably be submitted as a pull request to homebrew itself.

How would you like to proceed?
