### ISSUE TITLE
"Looking for ITK/VTK..." takes a very long time / Improve ImportTools

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#494]
Investigate the reason for the long configure time. Maybe it is related to the recursive library dependency declaration originally used by ITK or older CMake versions/projects (cf. ```basis_target_link_libraries```).

```
list (APPEND DEPENDS ${ARGS})
    # pull implicit dependencies (e.g., ITK uses this)
    set (DEPENDENCY_ADDED 1)
    while (DEPENDENCY_ADDED)
      set (DEPENDENCY_ADDED 0)
      foreach (LIB IN LISTS DEPENDS)
        foreach (LIB_DEPEND IN LISTS ${LIB}_LIB_DEPENDS)
          if (NOT LIB_DEPEND MATCHES "^$|^general$")
            string (REGEX REPLACE "^-l" "" LIB_DEPEND "${LIB_DEPEND}")
            list (FIND DEPENDS ${LIB_DEPEND} IDX)
            if (IDX EQUAL -1)
              list (APPEND DEPENDS ${LIB_DEPEND})
              set (DEPENDENCY_ADDED 1)
            endif ()
          endif ()
        endforeach ()
      endforeach ()
    endwhile ()
```

**Comment by schuhschuh** [comment]
Actually, the issue could be rather related to the functions defined in the BASIS ```ImportTools.cmake``` which called for each target in the ```ITKTargets.cmake``` file (i.e., the exported ITK targets to be imported).

**Comment by schuhschuh** [comment]
Awesome, it seems this bug was finally fixed in CMake 3.3! A more efficient ```set_target_properties``` implementation should thus be feasible for CMake versions >=3.3.

**Comment by schuhschuh** [comment]
The inefficiency of the ITK targets import is further related to the calls to ```basis_update_imported_type``` and ```basis_update_imported_location```, both called by ```set_target_properties```.

**Comment by ahundt** [comment]
that sounds fantastic!

**Comment by schuhschuh** [comment]
The before mentioned bug fix of CMake's ```macro/function``` commands is unfortunately not sufficient to get rid of the overloaded ```set_target_properties``` function of BASIS. However, the only reason this function is overridden is to be able to collect global information about all imported (executable) targets within a project and the location of the respective binary file for addition to the executable target info structure of the BASIS Utilities (cf. ```UtilitiesTools.cmake``` use of "project properties" named ```IMPORTED_TARGETS``` et al.).

A project which does not use or need this feature, should be able to disable the inclusion of the ```ImportTools.cmake``` all together. The only problem is that other BASIS functions call ```_set_target_properties```, i.e., the original CMake command to avoid the performance penalty of the overridden function. Now when the command is however not overridden, CMake does not recognise the ```_set_target_properties``` call. This is IMHO a flaw in CMake and should be reported.

Another reason for the inefficiency of the custom ```set_target_properties``` function is another issue with CMake's ```macro/function``` commands. It is not possible to pass a list of lists to the original CMake command, i.e., the dummy macro:
```cmake
macro (set_target_properties)
  _set_target_properties(${ARGV})
endmacro ()
```
causes an error when one of the property values is a list, e.g.,
```cmake
set_target_properties(foo PROPERTIES IMPORTED_INTERFACE_LINK_LIBRARIES "a;b")
```
because then ```_set_target_properties``` assumes that ```b``` is the name of another property to be set.

**Comment by schuhschuh** [comment]
Instead of trying to collect information about all imported targets within a project which is only needed for the executable target info tables of the BASIS Utilities when a project is split into separate modules/subprojects, another approach would be to generate source files with only a subset of this table for each module and to then somehow link them together in the end.

**Comment by schuhschuh** [comment]
I have removed the include of the ```ImportTools.cmake``` from ```BasisTools.cmake``` and replaced calls to ```_set_target_properties``` by ```set_target_properties```. This resolves the performance issue.

TODO: Add entries for executable targets imported by modules to the executable target info tables of the BASIS Utilities even without the functions defined by ImportTools.cmake. When done, remove this file.
