### ISSUE TITLE
Bootstrapping function should make BASIS_INSTALL_PREFIX advanced

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#502]
After the second run, when the user decided not to set the ```BASIS_INSTALL_PREFIX```, it should probably be declared as advanced option.

**Comment by ahundt** [comment]
Are you sure about that one? Benefits seem minimal, but it is not really a big deal either way.

**Comment by schuhschuh** [comment]
It's just a small change. I just would lije to hide any (posdibly
unused/uneanted) BASIS related variables from those seen by users of a
project. Of course developers could mark it advanced in their root
CMakeLists.txt or Settings.cmake files themselves.

**Comment by ahundt** [comment]
makes sense
