### ISSUE TITLE
Add HAVE_<PKG> definitions for found dependencies

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#503]
For optional dependencies, it is useful to have a compile definition for conditional code paths. Alternative name, ```HAS_<PKG>```.

**Comment by ahundt** [comment]
Good idea! I vote for HAVE_<PKG> that is used by many large and widely used libraries, such as OpenCV for example. Haven't seen HAS_<PKG> nearly as often.

**Comment by schuhschuh** [comment]
Good, I was also going to use it. It's just that the software I work on now
used to to use HAS_ ... but I'd rather change the code to use HAVE_.

**Comment by schuhschuh** [comment]
A ```HAVE_<PKG>``` compile definition is added for each found dependency (incl. required dependencies).

**Comment by schuhschuh** [comment]
- [ ] Document this in the user manual.

**Comment by schuhschuh** [comment]
Instead of just adding a single ```HAVE_<PKG>``` definition for a package, it would also be good to have individual definitions for each component/module that was found. For example, ```HAVE_<PKG>_ComponentA```, ```HAVE_<PKG>_ComponentB```...

**Comment by schuhschuh** [comment]
It may actually be better if (imported) targets (i.e., libraries build as part of a project module that were exported) would define ```HAVE_<PKG>_<TARGET>``` as part of their ```INTERFACE_COMPILE_DEFINITIONS```.

This means CMake BASIS would need to require version 2.8.12 or later (or only use these target properties when available). I am happy to drop support for older CMake versions.

**Comment by ahundt** [comment]
how would that work? perhaps there is a link to that functionality?

**Comment by schuhschuh** [comment]
Using the [target_compile_definitions](https://cmake.org/cmake/help/v2.8.12/cmake.html#command:target_compile_definitions) and generator expressions. Not sure how this can be "supported" by BASIS. It may more or less be in the responsible of the project developers themselves.

Provider:
```cmake
add_library(foo src/foo.cxx include/foo.h src/utils.h)
target_include_directories(foo PUBLIC include PRIVATE src)
target_compile_definitions(foo INTERFACE HAVE_FooProject_foo)
export(TARGETS foo NAMESPACE FooProject:: FILE FooExports.cmake)
```

Client:
```cmake
find_package(FooProject COMPONENTS foo) # not REQUIRED
add_executable(bar bar.cxx)
if (TARGET FooProject::foo)
  target_link_libraries(bar FooProject::foo)
  # the following I believe is implicitly done by target_link_libraries already and should be skipped
  target_compile_definitions(bar PRIVATE $<TARGET_PROPERTY:FooProject::foo,INTERFACE_COMPILE_DEFINITIONS>)
endif ()
```
Then, in the source code ```bar.cxx```, one can use the compile definition:
```cxx
#include <iostream>
int main()
{
#ifdef HAVE_FooProject_foo
  std::cout << "Enable features which depend on foo library" << std::endl;
#endif
  return 0;
}
```

**Comment by ahundt** [comment]
looks good!
