### ISSUE TITLE
Use DEPENDS_<PKG>_DIR cache entries for each dependency

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#505]
For each dependency, the user should only have to set a single path, either the installation root directory (prefix) or the location of the CMake package configuration file (```<PKG>Config.cmake``` or ```<pkg>-config.cmake```). The latter is specified using a ```<PKG>_DIR``` variable. These variables are, however, not grouped nicely together because of the lack of a common prefix. Further, one can argue that expert users expect those variables to always point to the location of a CMake configuration file (though I disagree with this interpretation).

CMake BASIS should define a single cache entry for each dependency, named ```DEPENDS_<PKG>_DIR```. The internal ```<PKG>_DIR``` variable is set to the value of this user path, possibly after appending the package specific subdirectory where the CMake configuration file is located.

**Comment by schuhschuh** [comment]
Implemented in the ```mirtk``` branch of the [CMake BASIS Modules](https://github.com/schuhschuh/cmake-basis-modules/commit/cd21fc94f12883aa6b5fcfcbc057a0879ef95d4d).

**Comment by schuhschuh** [comment]
- [ ] Document ```DEPENDS_<PKG>_DIR``` cache entries in user manual and generic installation guide.
- [ ] Make user aware that cache entry is only shown (non-advanced) when the dependency was not found. Otherwise the cache entry is marked as advanced and may be hidden from the GUI.
- [ ] Recommend "grouping" of variables in GUI or search for "DEPENDS" to only via the list of variables pointing to the location of the used dependencies for the build of the project.

**Comment by ahundt** [comment]
Does this have potential for some unusual failure cases, particularly when third party libraries aren't implemented in the most standardized way?

**Comment by schuhschuh** [comment]
Possibly, but this means these packages or the respectively Find modules also don't respect variables such as ```<PKG>_DIR``` which BASIS always used as main variable (and still does to initialise DEPENDS_<PKG>_DIR, it's really just a renaming). If a package does not behave well, addition of a proper Find module to BASIS that works well with the BASIS assumptions is probably the best.

**Comment by schuhschuh** [comment]
Standard CMake Find module variables are documented now [here](https://cmake.org/cmake/help/v3.4/manual/cmake-developer.7.html#standard-variable-names).

Note that while the CMake consensus is to call these variables ```<Pkg>_*```, CMake BASIS deliberately uses the ```DEPENDS_``` prefix for the one hybrid variable for each package that should be displayed to the user and is set to either the ```<Pkg>_ROOT_DIR``` or ```<Pkg>_DIR```. All other variables are either advanced or not cached. The common ```DEPENDS_``` prefix allows those variables to be grouped in the CMake GUI. Add non-cached boolean option to ```BasisSettings.cmake``` which can be overridden by developers in their project ```Settings.cmake``` file to request the use of ```<Pkg>_ROOT_DIR``` for packages found by MODULE mode (i.e., Find\<Pkg\>.cmake) and ```<Pkg>_DIR``` for packages found by CONFIG mode of ```find_package```.

- [ ] Set ```DEPENDS_<Pkg>_DIR``` to ```<Pkg>_ROOT_DIR``` when set before/after ```find_package```.
