### ISSUE TITLE
Maintain lean repository of BASIS CMake modules only for use as Git submodule

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#506]
For projects using Git (possibly also others), it would be great to have a lean version of the CMake BASIS repository which only contains the necessary files to be included in the project source tree as Git submodule. This could be the yet empty [cmake-basis-modules](https://github.com/schuhschuh/cmake-basis-modules) repository. I would only include the CMake modules currently located in ```src/cmake/```. If a project requires the BASIS Utilities, it will have to require a (separate) BASIS installation, resp. the bootstrapping of the entire BASIS.

**Comment by schuhschuh** [comment]
The current CMake BASIS itself (for being itself a project depending on the BASIS CMake modules) would be including this core repository as Git submodule.

**Comment by schuhschuh** [comment]
Further, when a project defines a ```BASIS_MODULE_PATH``` pointing to the subdirectory into which the CMake BASIS Modules are cloned by git submodule, the ```basis_project_begin``` macro should not automatically add ```BASIS``` as dependency. When a project includes the core modules as submodule and requires the CMake BASIS Utilities, it has to explicitly state this dependency in the ```BasisProject.cmake``` file. This dependency is only implied when ```BASIS_MODULE_PATH``` is not set and hence be set by the ```BASISConfig.cmake``` file included as part of the ```find_package(BASIS)``` call.

**Comment by schuhschuh** [comment]
- [ ] Modify bootstrapping script to initialise submodules when cloning CMake BASIS.

**Comment by schuhschuh** [comment]
TODO: Need to find a better way to cross-reference issues from commits to the submodule repository.

**Comment by ahundt** [comment]
What will this help with? Btw you could potentially use subtrees here, particularly for the cross referencing since everything relevant would be present for both trees.

**Comment by schuhschuh** [comment]
Thanks, I will look into subtrees. The benefit is that you can only
included the needed CMake modules in your project tree. No need for all the
other stuff.

**Comment by schuhschuh** [comment]
After having read a tutorial on Git subtrees, I think its perfect for
integrating the BASIS CMake Modules tree into the main BASIS repository
without squashing. It's also a viable option with squashing for users of
BASIS as they keep their own copy of the files in their repositories which
might make things clearer/easier. If they don't squash they might have a
problem with incorrect issue references from the BASIS commits though that
could interfere with their project's issues. For a user, I guess either
subtree or submodule would be fine. They can choose according to their
preferences. Will document both use cases.

**Comment by schuhschuh** [comment]
> What will this help with?

Adaptation of BASIS. No need for an extra bootstrapping build or previous installation of BASIS. For projects which really only need the CMake modules/functions of BASIS (probably the majority), it is more attractive to just copy those into their source tree / source distribution package. These don't require any build/installation.

**Comment by ahundt** [comment]
seems sensible!
