### ISSUE TITLE
Add BUILD_DOCUMENTATION and/or BUILD_EXAMPLE only when CMakeLists.txt found

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#519]
Currently, these options are added when the ```PROJECT_DOC_DIR``` and/or ```PROJECT_EXAMPLE_DIR``` exists even when these directories are empty or do not contain a required ```CMakeLists.txt``` file. Considering that projects may have such directories which do not require any built, add the options only when a ```CMakeLists.txt``` file is found.

**Comment by ahundt** [comment]
Perhaps it would also make sense to handle when the directories simply don't exist? Or is that already taken care of?

**Comment by schuhschuh** [comment]
> Perhaps it would also make sense to handle when the directories simply don't exist? Or is that already taken care of?

That's how it has been. Now instead it requires an existence of the CMakeLists.txt file within those directories, which implicitly checks for existence of the directory ;-).
