### ISSUE TITLE
Add NO_STANDARD_INPUT option to basis_add_doxygen_doc

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#535]
This option can be used to not add any CMake BASIS files to the list of input files.

**Comment by ahundt** [comment]
perhaps a different name from no_standard_input should be used? maybe NO_DEFAULT_INPUTS, still not great, perhaps there is even some other alternative name that is more abundantly clear.

**Comment by schuhschuh** [comment]
Yes, I am also not happy about the name. Just needed a quick option for my project. Will change this.

**Comment by schuhschuh** [comment]
Added ```basis_add_doxygen_doc``` options ```EXCLUDE_BASIS_MODULES``` and ```EXCLUDE_BASIS_UTILITIES``` instead of ```NO_STANDARD_INPUT```.
