### ISSUE TITLE
micromodules

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#538]
In the project I'm developing sometimes there are single library files or executable files that add new dependencies, so they are much too small to be a full module because the source code would simply get too confusing. However it may make sense to have some sort of "micro module" concept that lets us take advantage of the module enabling and disabling functionality for that component. 

These dependencies make code much harder for new users to set up, so being able to easily disable those components could be very useful. I don't have any advice of value on how to implement this yet.

What do you think of the idea of micromodules?

**Comment by schuhschuh** [comment]
Sounds like you would like to have an option for each build target (or groups of targets) and enabling a target (group) would enable all the other target (groups) that it depends on? Given that in this case we would not use special "meta-data" files such as BasisProject.cmake, this would probably rather re-use the information about inter-target dependencies recorded by ```basis_target_link_libraries``` and ```basis_add_dependencies```. Probably even CMake itself has target properties that record these dependencies. So then we need a command to add an option for some targets that can be enabled/disabled together such as

```cmake
basis_add_executable(foo1 foo1.cxx)
basis_add_library(bar1 SHARED bar1.cxx)
basis_targets_build_option(grp1 foo1 bar1)

basis_add_executable(foo2 foo2.cxx)
```

**Comment by ahundt** [comment]
interesting, well in projects like opencv there is sometimes a BUILD_WITH_<dep> option.

Possibly relevant stackoverflow items that control the all target and install step:
- https://stackoverflow.com/questions/13381742/cmake-exclude-executable-during-install
- https://stackoverflow.com/questions/14874702/is-there-a-generic-way-for-disabling-executable-targets-in-cmake
