### ISSUE TITLE
Refactor Find<Pkg>.cmake modules

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#542]
CMake has finally documented [standard variables](https://cmake.org/cmake/help/v3.4/manual/cmake-developer.7.html#standard-variable-names) and [how to implement and document a Find module](https://cmake.org/cmake/help/v3.4/manual/cmake-developer.7.html#a-sample-find-module) using reStructuredText. Also, use the CMake suggested Find module license to enable contribution of these modules upstream. The Find modules should use ```<Pkg>_ROOT``` instead of ```<Pkg>_DIR``` for the base directory, i.e., installation prefix of the found package. This variable should be set by ```basis_find_package``` to ```DEPENDS_<Pkg>_DIR```.

**Comment by schuhschuh** [comment]
Remove ```FindGTest.cmake``` from BASIS and use CMake module instead.

**Comment by ahundt** [comment]
I suggest removing FindOpenCV.cmake as well. For current versions they provide a `*Config.cmake` file
