### ISSUE TITLE
Add PROJECT_MODULES_DIRS

### ISSUE THREAD

**Issue by schuhschuh** [cmake-basis/legacy#543]
Instead of just a single ```PROJECT_MODULES_DIR```, it would be nice to be able to provide more than one directory which should be searched for a number of modules. Currently, when different groups of modules are located in different subdirectories, the developer can only specify one of these directories with ```MODULES_DIR``` option of ```basis_project``` and has to specify each module in another subdirectory tree using ```MODULE_DIRS``` explicitly.

**Comment by ahundt** [comment]
Perhaps an enumeration of the location of the actual modules rather than directories to search would be better?

**Comment by schuhschuh** [comment]
Well that is already possible using MODULE_DIRS. But then you have to edit the BasisProject.CMake file everything you add another module. Also, maybe it is not fixed which modules to expect, e.g., because of optional additional download of subdirectories.

**Comment by schuhschuh** [comment]
Maybe I misunderstood what you mean by "actual modules". A module is defined by its root directory and the BasisProject.cmake therein. The name of the directory generally relates to the module name.

**Comment by ahundt** [comment]
oh yeah silly me :-)
